baseURL = "http://mts-lending-page.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "MTS Lending Page"
[markup.goldmark.renderer]
unsafe = true
